version: "3"

services:
  count_together:
    image: aymericbernard/count-together:latest
    container_name: count_together
    restart: always
    environment:
      - VIRTUAL_HOST=count-together.example.com
      - LETSENCRYPT_HOST=count-together.example.com
      - LETSENCRYPT_EMAIL=contact@example.com
      - APP_SHORT_NAME=CounT
      - NGX_backendUrl="https://count-together-backend.example.com"
      - NGX_websiteUrl="https://count-together.example.com"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
